classDiagram
class Bus {
    +BusId: string
    +Model: BusModel
    +BatteriKapacitetKWh: double
    +BatteriNiveauProcent: double
    +ForbrugKWhPrKm: double
    +Status: BusStatus
    +ErKritisk: bool                 %% BatteryLevel < 20 %
    +BeregnOpladningstid(kW: double): TimeSpan
}

class BusModel {
    <<enumeration>>
    MBeCitaro
    YutongE12
    BYDK9
    Volvo7900E
}

class BusStatus {
    <<enumeration>>
    PåRute
    Afløser
    Returnerer
    Oplader
    Garage
}

Bus --> BusModel
Bus --> BusStatus
