sequenceDiagram
actor Driftsmedarbejder
participant System

Driftsmedarbejder ->> System: HentKritiskeBusser()
System -->> Driftsmedarbejder: Liste <Bus>

Driftsmedarbejder ->> System: MarkerTilOpladning(busId)
System -->> Driftsmedarbejder: Bekræft

Driftsmedarbejder ->> System: MarkerKlar(busId)
System -->> Driftsmedarbejder: Bekræft

Driftsmedarbejder ->> System: ForeslåOpladning(busId)
System -->> Driftsmedarbejder: TimeSpan

Note over System: System sender<br/>Notifikation(busId)<30 % - event
