sequenceDiagram
actor Driftsmedarbejder
participant System

Driftsmedarbejder ->> System: Start program
System -->> Driftsmedarbejder: Data indlæst

Driftsmedarbejder ->> System: Luk program
System -->> Driftsmedarbejder: Data gemt

Driftsmedarbejder ->> System: Tag manuel backup
System -->> Driftsmedarbejder: Backup-fil oprettet
