sequenceDiagram
actor Driftsmedarbejder
participant System as "BusAdministrations-system"

Driftsmedarbejder ->> System: HentAlleBusser()
System -->> Driftsmedarbejder: ListeAfBusser

Driftsmedarbejder ->> System: OpretBus(BusId, BatteriKapacitet, Forbrug)
System -->> Driftsmedarbejder: BekræftOprettet

Driftsmedarbejder ->> System: OpdaterBus(BusId, nyeStamdata)
System -->> Driftsmedarbejder: BekræftOpdateret

Driftsmedarbejder ->> System: FjernBus(BusId)
System -->> Driftsmedarbejder: BekræftFjernet
